### ISSUE TITLE
Emulator reset is broken

### ISSUE THREAD

**Issue by daid** [gbdev/rgbds-live#28]
Not sure what all was changed around this, but emulator reset no longer works properly.

If you run this example:
https://raw.githubusercontent.com/daid/gameboy-assembly-by-example/master/graphics/sprites.asm

The first run is fine, and the 2nd run after a reset has corrupted sprites. Indicating that something went wrong with VRAM access, which is odd that it only happens the 2nd time.

**Comment by SelvinPL** [comment]
it's problem with low part of rom
add
```
SECTION "blank", ROM0[$0]
  jp start
  ds $10-@, 0  
```

**Comment by ISSOtm** [comment]
Wait, that would mean the emulator starts at PC=0 when reset, instead of PC=$100? That's a problem.

**Comment by SelvinPL** [comment]
it's seems to be problem with binjgb - what i belive it happens that emulator "hides" lower addresses to long (if I understand it correctly on real hardware program starts from address 0 but not from rom but som internal bootrom)

**Comment by ISSOtm** [comment]
Yes, the console starts at 0 and runs a boot ROM that yields back control at $100, but that can be mostly papered over as if the console started at $100 in a post-boot ROM state directly.

The bug would be that the emulator starts at $100 the first time, but then at 0 when reset?

**Comment by SelvinPL** [comment]
hmm it is not bootrom ... this emulator doesn't even have bootrom ....
[this is offensive line](https://github.com/binji/binjgb/blob/main/src/common.c#L79)

wrapper.c: emulator_new_simple - lets observe rom_data passes from javascript
emulator.c: emulator_new - rom_data  is passed as init.rom.data(which is pointer)
set_rom_file_data init.rom is set to Emulator->file_data

then when you call emulator_delete it calls file_data_delete(&e->file_data)
and it calls xfree(file_data->data);

and if messing with input buffer which should not be freed but binjgb library

**Comment by SelvinPL** [comment]
eventually patching this file (common.c in binjgb library) to delete offensive line could help

**Comment by SelvinPL** [comment]
> it's problem with low part of rom add
> 
> ```
> SECTION "blank", ROM0[$0]
>   jp start
>   ds $10-@, 0  
> ```

hehe, before I posted this I was testing something and put `jp start` which is irrevelant here 
The point was that you need to fill at least $8-$10 bytes of rom to linker not put the stuff there

in OP's example `SECTION "graphics", ROM0` goes to address 0 and it is get frack but xfree error

**Comment by SelvinPL** [comment]
hmmm second option is to remove
free call from javascript code [here](https://github.com/gbdev/rgbds-live/blob/325da0b0bb6595fa6e26162b706b7a8357b5e730/js/emulator.js#L22)

**Comment by ISSOtm** [comment]
Er, that sounds like a much deeper issue. What I find puzzling is that binjgb [makes a copy of the ROM on load](<https://github.com/binji/binjgb/blob/38f2c2f59fe35d502b216ef2d08611de43dfe488/src/emulator.c#L4909>), so there should only be a single pointer to that ROM. (Put differently, we should *always* be `free`ing the ROM after calling `emulator_new_simple`.)

**Comment by SelvinPL** [comment]
this is not a copy but pointer assigment

**Comment by ISSOtm** [comment]
No:
```c
static Result set_rom_file_data(Emulator* e, const FileData* file_data) {
  CHECK_MSG(file_data->size > 0, "File is empty.\n");
  CHECK_MSG((file_data->size & (MINIMUM_ROM_SIZE - 1)) == 0,
            "File size (%ld) should be a multiple of minimum rom size (%ld).\n",
            (long)file_data->size, (long)MINIMUM_ROM_SIZE);
  e->file_data = *file_data;
  return OK;
  ON_ERROR_RETURN;
}
```

`*` in `*file_data` does dereference the pointer.

**Comment by SelvinPL** [comment]
sure ... but structure holds pointer

**Comment by ISSOtm** [comment]
Nope, [it holds a `FileData`](https://github.com/binji/binjgb/blob/38f2c2f59fe35d502b216ef2d08611de43dfe488/src/emulator.c#L698).

**Comment by SelvinPL** [comment]
I think this is solution https://github.com/gbdev/rgbds-live/issues/28#issuecomment-2359610482

**Comment by ISSOtm** [comment]
Yes, that would be correct. (I would add a comment right above `emulator_new_simple` that it takes ownership of the allocation, and will free it on its own when destroyed.)

**Comment by SelvinPL** [comment]
> Yes, that would be correct. (I would add a comment right above `emulator_new_simple` that it takes ownership of the allocation, and will free it on its own when destroyed.)

yeah, one year from now someone will add free again :D

**Comment by ISSOtm** [comment]
I cannot reproduce the error in the OP anymore. Why was the issue reopened?

**Comment by daid** [comment]
Looks fixed for this specific case, didn't check if is luck or if the timing is 100% the same now for both runs.
