### ISSUE TITLE
Allow passing flags to rgbasm/rgblink/rgbfix

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds-live#7]
These flags can significantly affect the assembly behavior and final ROM. You may want to blacklist certain flags which would prevent a proper build pipeline (e.g. `rgbasm -M` or `rgblink -O`), or just whitelist the sensible ones.

**Comment by SelvinPL** [comment]
with https://github.com/gbdev/rgbds-live/pull/36 you can pass it either with query string
`?asm=-M&link-O&fix-C`

ar via Options->Settings menu

(after adding via interface url option will be also added to url)

**Comment by ISSOtm** [comment]
Added by #36
