### ISSUE TITLE
RFC: How to maintain binjgb changes ?

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds-live#9]
rgbds-live requires a [modified version](https://github.com/binji/binjgb/compare/main...daid:binjgb:master) of the binjgb emulator, currently in a fork by Daid. @surma raised an interesting point about how those changes should be mantained.

Some alternatives:

1. Re-fork from Daid's binjgb under the gbdev org
   - This requires periodically rebasing against binji's upstream so we don't diverge
2. Maintain the changes as patches 
   - This requires manual work to update the patches when upstream changes (see what we already have to do for the RGBDS patch which breaks every time)
3. Discuss with @binji and see if we could PR them directly into upstream

**Comment by binji** [comment]
There aren't a lot of changes, I can push them upstream. Not quite as-is, since it would break other builds, but I can take a look.

**Comment by binji** [comment]
Changes landed upstream. You can pass `-DRGBDS_LIVE` to the build to enable the additional features.

**Comment by avivace** [comment]
Amazing, thanks @binji ! I've opened a small PR because I couldn't figure out how to pass such flag to make.. https://github.com/binji/binjgb/pull/48
